version: "3.8"
services:
  api-gateway:
    build: ./api-gateway-y81d
    container_name: api-gateway-y81d
    ports:
      - "8050:8050"
    depends_on:
      - auth-service-y81d
      - user-service-y81d
      - product-service-y81d
    environment:
      - PORT_APP=8050

  auth-service-y81d:
    build: ./auth-service-y81d
    container_name: auth-service-y81d
    ports:
      - "8052:8052"
    environment:
      - PORT_APP = 8052
      - JWT_SECRET = rahasia-super
      - USER_SERVICE_URL = http://user-service-y81d:8051
    depends_on:
      - user-service-y81d

  user-service-y81d:
    build: ./user-service-y81d
    container_name: user-service-y81d
    ports:
      - "8051:8051"
    environment:
      - PORT_APP = 8051
      - JWT_SECRET = rahasia-super
      - DB_USER = root
      - DB_PASSWORD = 123456789
      - DB_NAME = express-y81d-user-database
      - DB_HOST = 127.0.0.1

  product-service-y81d:
    build: ./product-service-y81d
    container_name: product-service-y81d
    ports:
      - "8053:8053"
    environment:
      - PORT_APP = 8053
      - JWT_SECRET = rahasia-super
      - DB_USER = root
      - DB_PASSWORD = 123456789
      - DB_NAME = express-y81d-product-database
      - DB_HOST = 127.0.0.1
      - USER_SERVICE_URL = http://user-service-y81d:8051