version: "3.8"
services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8050:8050"
    depends_on:
      - auth-service
      - user-service
      - product-service
    environment:
      - PORT_APP=8050

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8052:8052"
    environment:
      - PORT_APP=8052
      - JWT_SECRET=rahasia-super
      - USER_SERVICE_URL=http://user-service:8051
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8051:8051"
    environment:
      - PORT_APP=8051
      - JWT_SECRET=rahasia-super
      - DB_USER=root
      - DB_PASSWORD=123456789
      - DB_NAME=express-y81d-user-database
      - DB_HOST=127.0.0.1

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8053:8053"
    environment:
      - PORT_APP=8053
      - JWT_SECRET=rahasia-super
      - DB_USER=root
      - DB_PASSWORD=123456789
      - DB_NAME=express-y81d-product-database
      - DB_HOST=127.0.0.1
      - USER_SERVICE_URL=http://user-service:8051